### ISSUE TITLE
No Email is sent when a new chat is started

### ISSUE THREAD

**Issue by batataboy16** [dannyspanish/YoBro---WordPress-Private-Messaging-Plugin-Email-Notifications#1]
When a user sends the first message via "New -> New Message -> User selected and message sent", no email is being sent out. Just when the second message (and all oafter that" are sent, a email notification is being sent out.

**Comment by dannyspanish** [comment]
Is the default value of the column "email_sent" null?

**Comment by batataboy16** [comment]
Oh my, sorry yes that was my mistake. Thanks so much for the help!!
